"""Adapter SDK exports."""

from .base import AdapterContext, AdapterResult, BaseAdapter
from .biomedical import (
    ChEMBLAdapter,
    ClinicalTrialsAdapter,
    COREAdapter,
    CrossrefAdapter,
    ICD11Adapter,
    MeSHAdapter,
    OpenAlexAdapter,
    OpenFDADeviceAdapter,
    OpenFDADrugEventAdapter,
    OpenFDADrugLabelAdapter,
    PMCAdapter,
    RxNormAdapter,
    SemanticScholarAdapter,
    UnpaywallAdapter,
)
from .example import ExampleAdapter
from .registry import registry
from .testing import run_adapter
from .yaml_parser import AdapterConfig, create_adapter_from_config, load_adapter_config
from .plugins.base import BaseAdapterPlugin, ReadOnlyAdapterPlugin
from .plugins.config import (
    AdapterSettings,
    ConfigValidationResult,
    SettingsHotReloader,
    VaultSecretProvider,
    apply_env_overrides,
    migrate_yaml_to_env,
    validate_on_startup,
)
from .plugins.manager import AdapterHookSpec, AdapterPluginError, AdapterPluginManager
from .plugins.models import (
    AdapterCostEstimate,
    AdapterDomain,
    AdapterMetadata,
    AdapterRequest,
    AdapterResponse,
    AdapterResponseEnvelope,
    BiomedicalPayload,
    FinancialPayload,
    LegalPayload,
    Pagination,
    ValidationOutcome,
)
from .plugins.resilience import (
    BackoffStrategy,
    CircuitBreaker,
    CircuitState,
    ResilienceConfig,
    ResilientHTTPClient,
    circuit_breaker,
    rate_limit,
    retry_on_failure,
)

__all__ = [
    "AdapterConfig",
    "AdapterContext",
    "AdapterResult",
    "BaseAdapter",
    "COREAdapter",
    "ChEMBLAdapter",
    "ClinicalTrialsAdapter",
    "CrossrefAdapter",
    "ExampleAdapter",
    "AdapterHookSpec",
    "AdapterPluginError",
    "AdapterPluginManager",
    "AdapterCostEstimate",
    "AdapterDomain",
    "AdapterMetadata",
    "AdapterRequest",
    "AdapterResponse",
    "AdapterResponseEnvelope",
    "AdapterSettings",
    "BackoffStrategy",
    "BaseAdapterPlugin",
    "ICD11Adapter",
    "CircuitBreaker",
    "CircuitState",
    "MeSHAdapter",
    "OpenAlexAdapter",
    "OpenFDADeviceAdapter",
    "OpenFDADrugEventAdapter",
    "OpenFDADrugLabelAdapter",
    "PMCAdapter",
    "Pagination",
    "RxNormAdapter",
    "ResilienceConfig",
    "ResilientHTTPClient",
    "SettingsHotReloader",
    "SemanticScholarAdapter",
    "UnpaywallAdapter",
    "create_adapter_from_config",
    "circuit_breaker",
    "load_adapter_config",
    "migrate_yaml_to_env",
    "rate_limit",
    "registry",
    "retry_on_failure",
    "run_adapter",
    "validate_on_startup",
    "VaultSecretProvider",
    "apply_env_overrides",
    "BiomedicalPayload",
    "FinancialPayload",
    "LegalPayload",
    "ValidationOutcome",
    "ConfigValidationResult",
    "ReadOnlyAdapterPlugin",
]
