apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: staging-

images:
  - name: ghcr.io/example/medical-kg:latest
    newName: ghcr.io/example/medical-kg
    newTag: staging
  - name: ghcr.io/example/medical-kg-worker:latest
    newName: ghcr.io/example/medical-kg-worker
    newTag: staging
  - name: registry.example.com/medical-kg/vllm-qwen3:latest
    newName: ghcr.io/example/vllm-qwen3
    newTag: staging

patches:
  - target:
      kind: Deployment
      name: gateway
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
