apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/example/medical-kg:latest
    newName: ghcr.io/example/medical-kg
    newTag: latest
  - name: ghcr.io/example/medical-kg-worker:latest
    newName: ghcr.io/example/medical-kg-worker
    newTag: latest
  - name: registry.example.com/medical-kg/vllm-embedding:latest
    newName: ghcr.io/example/vllm-embedding
    newTag: latest

patches:
  - target:
      kind: Deployment
      name: gateway
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
