version: '3.8'
services:
  vllm-server:
    image: vllm/vllm-openai:v0.11.0
    command: >
      python -m vllm.entrypoints.openai.api_server \
        --model Qwen/Qwen2.5-VL-7B-Instruct \
        --host 0.0.0.0 \
        --port 8000 \
        --gpu-memory-utilization 0.92 \
        --max-model-len 32768 \
        --tensor-parallel-size 1 \
        --dtype auto \
        --enforce-eager
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "8000:8000"
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    networks:
      - medical-kg-net
networks:
  medical-kg-net:
    external: true
