name: ignored-by-path
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy>=2.3
  - py-opencv
  - ffmpeg
  - pip
  - ruff
  - black
  - mypy
  - pytest
  - pytest-cov
  - ipykernel
  - pre-commit
  - pip:
      - python-dotenv
      - mineru[gpu]
