site_name: Medical KG Documentation
repo_url: https://github.com/example/medical_kg_rev
theme:
    name: material
    features:
        - navigation.instant
        - navigation.tabs
        - content.code.copy
nav:
    - Home: index.md
    - Architecture:
          - Overview: architecture/overview.md
    - DevOps & Observability:
          - CI/CD Pipeline: devops/ci-cd.md
          - Local Environments: devops/local-environments.md
          - Observability: devops/observability.md
          - Kubernetes: devops/kubernetes.md
          - Retrieval Rollout Runbook: operations/retrieval-rollout.md
    - Retrieval:
          - User Guide: guides/retrieval/user-guide.md
          - Developer Guide: guides/retrieval/developer-guide.md
    - API Contracts:
          - REST OpenAPI: openapi.yaml
          - GraphQL SDL: schema.graphql
          - AsyncAPI: asyncapi.yaml
    - Pipeline API:
          - Coordinators: api/coordinators.md
          - Services: api/services.md
          - Embedding: api/embedding.md
          - Orchestration: api/orchestration.md
plugins:
    - search
    - mkdocstrings:
          handlers:
              python:
                  options:
                      show_source: true
                      show_root_heading: true
                      heading_level: 2
                      docstring_style: google
                      merge_init_into_class: true
                      show_signature_annotations: true
