"""Ingestion and retrieval orchestration primitives."""

from .kafka import KafkaClient, KafkaMessage
from .ledger import JobLedger, JobLedgerEntry, JobTransition
from .dagster import (
    DagsterOrchestrator,
    DagsterRunResult,
    PipelineConfigLoader,
    PipelineTopologyConfig,
    ResiliencePolicy,
    ResiliencePolicyConfig,
    ResiliencePolicyLoader,
    StageFactory,
    StageResolutionError,
    submit_to_dagster,
)
from .haystack import (
    HaystackChunker,
    HaystackEmbedder,
    HaystackIndexWriter,
    HaystackRetriever,
    HaystackSparseExpander,
)
from .stages import StageFailure, StageRegistry
from .stages.contracts import (
    ChunkStage,
    EmbedStage,
    EmbeddingBatch,
    EmbeddingVector,
    ExtractStage,
    GraphWriteReceipt,
    IngestStage,
    IndexReceipt,
    IndexStage,
    KGStage,
    ParseStage,
    StageContext,
)
from .retrieval_pipeline import (
    ConfigurableStage,
    FinalSelectorOrchestrator,
    FusionOrchestrator,
    QueryPipelineExecutor,
    RerankCache,
    RerankOrchestrator,
    RetrievalOrchestrator,
    StrategySpec,
)

__all__ = [
    "ChunkStage",
    "ConfigurableStage",
    "DagsterOrchestrator",
    "DagsterRunResult",
    "EmbedStage",
    "EmbeddingBatch",
    "EmbeddingVector",
    "FinalSelectorOrchestrator",
    "FusionOrchestrator",
    "GraphWriteReceipt",
    "HaystackChunker",
    "HaystackEmbedder",
    "HaystackIndexWriter",
    "HaystackRetriever",
    "HaystackSparseExpander",
    "IngestStage",
    "IndexReceipt",
    "IndexStage",
    "JobLedger",
    "JobLedgerEntry",
    "JobTransition",
    "KGStage",
    "KafkaClient",
    "KafkaMessage",
    "ParseStage",
    "PipelineConfigLoader",
    "PipelineTopologyConfig",
    "QueryPipelineExecutor",
    "ResiliencePolicy",
    "ResiliencePolicyConfig",
    "ResiliencePolicyLoader",
    "RerankCache",
    "RerankOrchestrator",
    "RetrievalOrchestrator",
    "StageContext",
    "StageFactory",
    "StageFailure",
    "StageRegistry",
    "StageResolutionError",
    "StrategySpec",
    "submit_to_dagster",
]
