name: pdf-two-phase
version: "2025-01-01"
applicable_sources:
  - pmc
  - pmc-fulltext
metadata:
  owner: ingestion-team
  description: PDF ingestion with MinerU gate.
plugins:
  stages:
    - callable: "Medical_KG_rev.orchestration.stage_plugins:register_download_stage"
    - callable: "Medical_KG_rev.orchestration.stage_plugins:register_gate_stage"
stages:
  - name: ingest
    type: ingest
    policy: default
  - name: download
    type: download
    policy: polite-api
    depends_on:
      - ingest
    config:
      sources:
        - kind: openalex
          attribute: best_pdf_url
    metadata_overrides:
      state_key: downloaded_files
      description: Resolve and persist PDF assets required for downstream OCR.
  - name: gate_pdf_ir_ready
    type: gate
    gate: pdf_ir_ready
    policy: default
    depends_on:
      - download
    config:
      conditions:
        - key: ledger.pdf_ir_ready
          expected: true
      timeout_seconds: 900
      poll_interval_seconds: 10
    metadata_overrides:
      dependencies:
        - "@ledger"
        - download
  - name: chunk
    type: chunk
    policy: gpu-bound
    depends_on:
      - gate_pdf_ir_ready
  - name: embed
    type: embed
    policy: gpu-bound
    depends_on:
      - chunk
  - name: index
    type: index
    policy: default
    depends_on:
      - embed
  - name: extract
    type: extract
    policy: gpu-bound
    depends_on:
      - chunk
  - name: kg
    type: knowledge-graph
    policy: default
    depends_on:
      - extract
      - index
gates:
  - name: pdf_ir_ready
    resume_stage: chunk
    timeout_seconds: 900
    poll_interval_seconds: 10.0
    condition:
      field: ledger.pdf_ir_ready
      equals: true
