name: pdf-two-phase
version: "2025-01-01"
applicable_sources:
  - openalex
metadata:
  owner: ingestion-team
  description: PDF ingestion with MinerU gate.
stages:
  - name: ingest
    type: ingest
    policy: polite-api
    config:
      adapter: openalex
  - name: download
    type: download
    policy: polite-api
    depends_on:
      - ingest
  - name: gate_vlm_ready
    type: gate
    policy: default
    depends_on:
      - download
  - name: chunk
    type: chunk
    policy: gpu-bound
    depends_on:
      - gate_vlm_ready
  - name: embed
    type: embed
    policy: gpu-bound
    depends_on:
      - chunk
  - name: index
    type: index
    policy: default
    depends_on:
      - embed
  - name: extract
    type: extract
    policy: gpu-bound
    depends_on:
      - chunk
  - name: kg
    type: knowledge-graph
    policy: default
    depends_on:
      - extract
      - index
gates:
  - name: vlm_processing_ready
    resume_stage: chunk
    condition:
      field: vlm_processing_ready
      equals: true
      timeout_seconds: 900
      poll_interval_seconds: 10.0
