global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: gateway
    metrics_path: /metrics
    static_configs:
      - targets:
          - gateway:8000
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090
  - job_name: jaeger
    metrics_path: /metrics
    static_configs:
      - targets:
          - jaeger:14269
  - job_name: loki
    metrics_path: /metrics
    static_configs:
      - targets:
          - loki:3100
