apiVersion: v1
kind: ConfigMap
metadata:
    name: cache-service-config
    namespace: medical-kg
data:
    redis.conf: |
        # Redis configuration for cache service
        port 6379
        bind 0.0.0.0
        protected-mode no
        appendonly yes
        appendfsync everysec
        maxmemory 2gb
        maxmemory-policy allkeys-lru
        save 900 1
        save 300 10
        save 60 10000

---
apiVersion: v1
kind: Service
metadata:
    name: cache-service
    namespace: medical-kg
    labels:
        app: cache-service
spec:
    selector:
        app: cache-service
    ports:
        - name: redis
          port: 6379
          targetPort: 6379
          protocol: TCP
    type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: cache-service
    namespace: medical-kg
    labels:
        app: cache-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: cache-service
    template:
        metadata:
            labels:
                app: cache-service
        spec:
            containers:
                - name: redis
                  image: redis:7-alpine
                  ports:
                      - containerPort: 6379
                  env:
                      - name: REDIS_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: cache-service-secrets
                                key: password
                  volumeMounts:
                      - name: redis-data
                        mountPath: /data
                      - name: redis-config
                        mountPath: /usr/local/etc/redis/redis.conf
                        subPath: redis.conf
                  resources:
                      requests:
                          memory: "512Mi"
                          cpu: "100m"
                      limits:
                          memory: "2Gi"
                          cpu: "500m"
                  livenessProbe:
                      tcpSocket:
                          port: 6379
                      initialDelaySeconds: 30
                      periodSeconds: 10
                  readinessProbe:
                      exec:
                          command:
                              - redis-cli
                              - ping
                      initialDelaySeconds: 5
                      periodSeconds: 5
            volumes:
                - name: redis-data
                  persistentVolumeClaim:
                      claimName: cache-service-pvc
                - name: redis-config
                  configMap:
                      name: cache-service-config

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: cache-service-pvc
    namespace: medical-kg
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi
    storageClassName: standard

---
apiVersion: v1
kind: Secret
metadata:
    name: cache-service-secrets
    namespace: medical-kg
type: Opaque
data:
    password: cmVkaXNfcGFzc3dvcmQ= # redis_password in base64
