---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: gpu-metrics-exporter
    namespace: medical-kg
spec:
    replicas: 1
    selector:
        matchLabels:
            app: gpu-metrics-exporter
    template:
        metadata:
            labels:
                app: gpu-metrics-exporter
        spec:
            containers:
                - name: gpu-metrics-exporter
                  image: medical-kg/gpu-metrics-exporter:latest
                  ports:
                      - containerPort: 8000
                        name: metrics
                  env:
                      - name: NVIDIA_VISIBLE_DEVICES
                        value: "all"
                      - name: NVIDIA_DRIVER_CAPABILITIES
                        value: "utility"
                  resources:
                      requests:
                          memory: "128Mi"
                          cpu: "100m"
                      limits:
                          memory: "256Mi"
                          cpu: "200m"
                  volumeMounts:
                      - name: nvidia-socket
                        mountPath: /var/run/nvidia-docker.sock
                        readOnly: true
            volumes:
                - name: nvidia-socket
                  hostPath:
                      path: /var/run/nvidia-docker.sock
            nodeSelector:
                accelerator: nvidia-tesla-k80

---
apiVersion: v1
kind: Service
metadata:
    name: gpu-metrics-exporter
    namespace: medical-kg
spec:
    selector:
        app: gpu-metrics-exporter
    ports:
        - port: 8000
          targetPort: 8000
          name: metrics
    type: ClusterIP

---
apiVersion: v1
kind: ServiceMonitor
metadata:
    name: gpu-metrics-exporter
    namespace: medical-kg
spec:
    selector:
        matchLabels:
            app: gpu-metrics-exporter
    endpoints:
        - port: metrics
          interval: 30s
          path: /metrics
