active_namespaces:
  - single_vector.qwen3.4096.v1
  - sparse.splade_v3.400.v1
  - multi_vector.colbert_v2.128.v1

namespaces:
  single_vector.qwen3.4096.v1:
    name: qwen3-embedding
    provider: vllm
    kind: single_vector
    model_id: Qwen/Qwen2.5-Embedding-8B-Instruct
    model_version: v1
    dim: 4096
    pooling: mean
    normalize: true
    batch_size: 64
    requires_gpu: true
    parameters:
      endpoint: http://vllm-embeddings:8001/v1
      timeout: 60
      max_tokens: 8192
      candidate_batch_sizes:
        - 32
        - 64
        - 128
      gpu_memory_fraction: 0.9
      gpu_memory_reserve_mb: 2048
  sparse.splade_v3.400.v1:
    name: splade-v3
    provider: pyserini
    kind: sparse
    model_id: naver/splade-v3
    model_version: v3
    dim: 400
    normalize: false
    batch_size: 32
    parameters:
      top_k: 400
      mode: document
      max_terms: 400
  multi_vector.colbert_v2.128.v1:
    name: colbert-v2
    provider: colbert
    kind: multi_vector
    model_id: colbert-v2
    model_version: v2
    dim: 128
    normalize: false
    batch_size: 16
    parameters:
      max_doc_tokens: 180
