model_type: vllm

service:
  host: 0.0.0.0
  port: 8001
  dtype: float16
  tensor_parallel_size: 1
model:
  name: "Qwen/Qwen2.5-Coder-1.5B"
  trust_remote_code: true
  download_dir: "/models/qwen3-embedding"
  revision: "main"
batching:
  max_batch_size: 64
  max_wait_time_ms: 50
  preferred_batch_size: 32
gpu:
  min_memory_mb: 12288
  memory_fraction: 0.8
  max_model_len: 512
health_check:
  enabled: true
  gpu_check_interval_seconds: 30
  fail_fast_on_gpu_unavailable: true
logging:
  level: INFO
  format: json
