name: spl-label
domain: label
chunker_type: spl_label
target_tokens: 400
overlap_tokens: 30
respect_boundaries:
  - section
  - table
sentence_splitter: scispacy
preserve_tables_as_html: true
filters:
  - drop_boilerplate
  - exclude_references
metadata:
  intent_hints:
    LOINC:34089-3 Indications: narrative
    LOINC:42348-3 Dosage: dose
    LOINC:39245-5 Warnings: safety
    LOINC:43995-0 Adverse Reactions: ae
  loinc_map:
    Indications: "34089-3"
    Dosage: "42348-3"
    Warnings: "39245-5"
    Adverse Reactions: "43995-0"
