# Reranking model registry describing available reranker variants.
default: bge-reranker-base
cache_dir: model_cache/rerankers
models:
  bge-reranker-base:
    display_name: BGE Reranker Base
    reranker_id: cross_encoder:bge
    provider: huggingface
    model_id: BAAI/bge-reranker-base
    revision: main
    version: v1.0
    requires_gpu: false
    description: Balanced quality reranker tuned for biomedical passages.
    metadata:
      languages: ["en"]
      latency_profile: medium
  ms-marco-minilm-l12-v2:
    display_name: MS MARCO MiniLM L-12 v2
    reranker_id: cross_encoder:minilm
    provider: huggingface
    model_id: cross-encoder/ms-marco-MiniLM-L-12-v2
    revision: main
    version: v2.1
    requires_gpu: false
    description: Low-latency MiniLM cross encoder suitable for CPU deployments.
    metadata:
      languages: ["en"]
      latency_profile: fast
  colbert-reranker-v2:
    display_name: ColBERT v2 Reranker
    reranker_id: late_interaction:colbert
    provider: huggingface
    model_id: colbert-ir/colbertv2.0
    revision: main
    version: v2.0
    requires_gpu: true
    description: Late interaction reranker offering strong recall for long passages.
    metadata:
      languages: ["en"]
      latency_profile: slow
