# Default reranking configuration for tenants.
# Tenants listed in the `tenants` map default to reranking without requiring
# callers to set the rerank flag explicitly. Other tenants participate in the
# experiment defined below.
default_enabled: false

# Explicit tenant defaults.
tenants:
  oncology: true
  cardiology: false

# Deterministic A/B experiment split controlling optional reranking.
experiment:
  rerank_ratio: 0.1
