apiVersion: apps/v1
kind: Deployment
metadata:
  name: mineru-workers
  namespace: medical-kg
spec:
  replicas: 8
  selector:
    matchLabels:
      app: mineru-worker
  template:
    metadata:
      labels:
        app: mineru-worker
    spec:
      containers:
        - name: mineru
          image: ghcr.io/your-org/mineru-worker:split-container
          env:
            - name: VLLM_SERVER_URL
              value: "http://vllm-server:8000"
            - name: MINERU_BACKEND
              value: "vlm-http-client"
          resources:
            requests:
              cpu: "2000m"
              memory: "4Gi"
            limits:
              cpu: "4000m"
              memory: "8Gi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
