apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap-gateway.yaml
  - configmap-vllm-server.yaml
  - secret-sentry.yaml
  - deployment-gateway.yaml
  - deployment-ingest-worker.yaml
  - deployment-vllm-embedding.yaml
  - deployment-vllm-server.yaml
  - deployment-mineru-workers.yaml
  - service-gateway.yaml
  - service-vllm-embedding.yaml
  - service-vllm-server.yaml
  - networkpolicy-vllm-server.yaml
  - pvc-huggingface-cache.yaml
  - ingress.yaml
  - hpa-gateway.yaml
  - servicemonitor-vllm-server.yaml
