apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap-gateway.yaml
  - secret-sentry.yaml
  - deployment-gateway.yaml
  - deployment-ingest-worker.yaml
  - service-gateway.yaml
  - ingress.yaml
  - hpa-gateway.yaml
