apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
    - namespace.yaml
    - configmap-gateway.yaml
    - configmap-vllm-server.yaml
    - secret-sentry.yaml
    - deployment-gateway.yaml
    - deployment-ingest-worker.yaml
    - deployment-vllm-embedding.yaml
    - deployment-vllm-server.yaml
    - service-gateway.yaml
    - ingress.yaml
    - hpa-gateway.yaml
    - servicemonitor-vllm-server.yaml
