apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
<<<<<<< HEAD
    - namespace.yaml
    - configmap-gateway.yaml
    - configmap-vllm-server.yaml
    - secret-sentry.yaml
    - deployment-gateway.yaml
    - deployment-ingest-worker.yaml
    - deployment-vllm-embedding.yaml
    - deployment-vllm-server.yaml
    - service-gateway.yaml
    - ingress.yaml
    - hpa-gateway.yaml
    - servicemonitor-vllm-server.yaml
=======
  - namespace.yaml
  - configmap-gateway.yaml
  - secret-sentry.yaml
  - deployment-gateway.yaml
  - deployment-ingest-worker.yaml
  - deployment-vllm-qwen3.yaml
  - service-gateway.yaml
  - service-vllm-qwen3.yaml
  - ingress.yaml
  - hpa-gateway.yaml
>>>>>>> refs/remotes/origin/codex/implement-add-embeddings-representation-proposal-ae4adw
