name: Documentation Quality Checks

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
        paths:
            - "src/Medical_KG_rev/gateway/**"
            - "src/Medical_KG_rev/services/**"
            - "src/Medical_KG_rev/orchestration/**"
            - "scripts/check_documentation.py"
            - ".pre-commit-config.yaml"
            - "pyproject.toml"

jobs:
    documentation-checks:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install ruff pydocstyle mypy
                  pip install -e .

            - name: Run ruff linting
              run: |
                  ruff check src/Medical_KG_rev/gateway src/Medical_KG_rev/services src/Medical_KG_rev/orchestration

            - name: Run ruff formatting check
              run: |
                  ruff format --check src/Medical_KG_rev/gateway src/Medical_KG_rev/services src/Medical_KG_rev/orchestration

            - name: Run docstring checks
              run: |
                  ruff check --select D src/Medical_KG_rev/gateway src/Medical_KG_rev/services src/Medical_KG_rev/orchestration

            - name: Run pydocstyle checks
              run: |
                  pydocstyle --convention=google --add-ignore=D100,D101,D102,D103,D104,D105,D106,D107 src/Medical_KG_rev/gateway src/Medical_KG_rev/services src/Medical_KG_rev/orchestration

            - name: Run type checking
              run: |
                  mypy --strict src/Medical_KG_rev/gateway src/Medical_KG_rev/services src/Medical_KG_rev/orchestration

            - name: Run custom documentation checker
              run: |
                  python scripts/check_documentation.py --verbose

            - name: Run pre-commit hooks
              run: |
                  pip install pre-commit
                  pre-commit run --all-files

    security-checks:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install bandit safety

            - name: Run bandit security check
              run: |
                  bandit -r src/Medical_KG_rev/ -f json -o bandit-report.json || true
                  bandit -r src/Medical_KG_rev/ -f txt

            - name: Run safety check
              run: |
                  safety check --json --output safety-report.json || true
                  safety check

    documentation-generation:
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install mkdocs mkdocstrings[python] mkdocs-material

            - name: Build documentation
              run: |
                  mkdocs build --strict

            - name: Upload documentation artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: documentation-site
                  path: site/
                  retention-days: 30
